;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua-cut-region
        cua-paste
        typescript-insert-and-indent
        ))

(setq mc/cmds-to-run-once
      '(
        multiple-cursors-hydra/mc/edit-lines-and-exit
        multiple-cursors-hydra/mc/mark-all-like-this-and-exit
        multiple-cursors-hydra/mc/mark-next-like-this
        multiple-cursors-hydra/mc/skip-to-next-like-this
        multiple-cursors-hydra/mc/skip-to-previous-like-this
        multiple-cursors-hydra/mc/unmark-next-like-this
        multiple-cursors-hydra/nil
        ))
