;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-indent-line-or-region
        cua-copy-region
        cua-cut-region
        cua-paste
        delete-indentation
        forward-sexp
        indent-for-tab-command
        markdown-cycle
        paredit-backward
        paredit-forward
        pbpaste
        sh-assignment
        shell-pop
        smex
        typescript-insert-and-autoconvert-to-template
        typescript-insert-and-indent
        what-cursor-position
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        compose-mail
        kill-region
        lsp-find-references
        markdown-outdent-or-delete
        multiple-cursors-hydra/body
        multiple-cursors-hydra/mc/edit-lines-and-exit
        multiple-cursors-hydra/mc/mark-all-like-this-and-exit
        multiple-cursors-hydra/mc/mark-next-like-this
        multiple-cursors-hydra/mc/mark-previous-like-this
        multiple-cursors-hydra/mc/skip-to-next-like-this
        multiple-cursors-hydra/mc/skip-to-previous-like-this
        multiple-cursors-hydra/mc/unmark-next-like-this
        multiple-cursors-hydra/nil
        xref-find-references
        xterm-paste
        ))
